//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clouctech_wbl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_isEntities : DbContext
    {
        public db_isEntities()
            : base("name=db_isEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_report> tb_report { get; set; }
        public virtual DbSet<tb_stock> tb_stock { get; set; }
        public virtual DbSet<tb_transaction> tb_transaction { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
    }
}
