//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clouctech_wbl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_report
    {
        public int r_id { get; set; }
        public System.DateTime r_date { get; set; }
        public int r_stock { get; set; }
    
        public virtual tb_stock tb_stock { get; set; }
    }
}
