//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clouctech_wbl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tb_stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_stock()
        {
            this.tb_report = new HashSet<tb_report>();
            this.tb_transaction = new HashSet<tb_transaction>();
        }

        public int s_id { get; set; }

        [DisplayName("Name")]
        public string s_name { get; set; }

        [DisplayName("Quantity")]
        public Nullable<int> s_qtty { get; set; }

        [DisplayName("Modal")]
        public Nullable<double> s_modal { get; set; }

        [DisplayName("Price per tin")]
        public Nullable<double> s_hargatin { get; set; }

        [DisplayName("Vending")]
        public string s_vending { get; set; }

        [DisplayName("Profit per tin")]
        public Nullable<double> s_untungtin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_report> tb_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_transaction> tb_transaction { get; set; }
    }
}
