//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clouctech_wbl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tb_transaction
    {

        public int t_id { get; set; }

        [DisplayName("Stock Name")]
        public int s_id { get; set; }

        [DisplayName("Quantity Sold")]
        public int t_qttyjual { get; set; }

        [DisplayName("Topup Quantity")]
        public int t_topup { get; set; }

        [DisplayName("Profit")]
        public double t_untung { get; set; }

        [DisplayName("Tunai slot")]
        public double t_tunaislot { get; set; }

        public virtual tb_stock tb_stock { get; set; }
    }
}
