//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clouctech_wbl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_user
    {
        [DisplayName("User ID")]
        [Required(ErrorMessage = "This field is mandatory.")]
        public string u_id { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is mandatory.")]
        public string u_pwd { get; set; }

        [DisplayName ("Name")]

        public string u_name { get; set; }

        [DisplayName ("Contact")]

        public string u_contact { get; set; }

        [DisplayName ("User Type")]

        public int u_type { get; set; }

        [DisplayName("Email")]

        public string u_email { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
